version: '3.8'
services:
  nginx:
    container_name: curso_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./source:/usr/share/nginx/html:ro
